---

- name: Setup Ubuntu Server
  hosts: all
  become: yes

  roles:
    #- role: wifi_ap
    - role: headless
    - role: setup_mongodb
    - role: setup_apache

  tasks:
    - name: Install the One True Editor
      apt:
        name: emacs-nox
        state: present
